# Generated by Django 2.1 on 2019-03-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190309_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanatorium',
            fields=[
                ('id_Sanatorium', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='sanatorium/')),
            ],
        ),
    ]
