# Generated by Django 2.1 on 2019-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190311_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatorium',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='sanatoriums'),
        ),
    ]
