# Generated by Django 2.1 on 2019-03-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190309_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinique',
            name='document',
        ),
        migrations.AddField(
            model_name='clinique',
            name='Image',
            field=models.ImageField(blank=True, upload_to='cliniques/'),
        ),
    ]
